# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simple.proto import user_pb2 as proto_dot_user__pb2


class UserStub(object):
    """定义User rpc服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUser = channel.unary_unary(
                '/proto.User/AddUser',
                request_serializer=proto_dot_user__pb2.UserRequest.SerializeToString,
                response_deserializer=proto_dot_user__pb2.UserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/proto.User/GetUser',
                request_serializer=proto_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=proto_dot_user__pb2.GetUserResponse.FromString,
                )


class UserServicer(object):
    """定义User rpc服务
    """

    def AddUser(self, request, context):
        """定义rpc服务的方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=proto_dot_user__pb2.UserRequest.FromString,
                    response_serializer=proto_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=proto_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=proto_dot_user__pb2.GetUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """定义User rpc服务
    """

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.User/AddUser',
            proto_dot_user__pb2.UserRequest.SerializeToString,
            proto_dot_user__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.User/GetUser',
            proto_dot_user__pb2.GetUserRequest.SerializeToString,
            proto_dot_user__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
